//images
import bubbleImg from "../../assets/Bubble-Sort-Algorithm-930x620.png";
import insertionImg from "../../assets/Insertion.png";
import selectionImg from "../../assets/Selection.png";
import mergeImg from "../../assets/merge.png";
import quickImg from "../../assets/Quick.png";
import heapImg from "../../assets/Heap.png";
import countingImg from "../../assets/counting_sort.png";
import linearSearchImg from "../../assets/linear.png";
import binarySearchImg from "../../assets/binary_search.png";
import jumpSearchImg from "../../assets/jump_search.png";
import interpolationSearchImg from "../../assets/interpolation.png";
import exponentialSearchImg from "../../assets/exponential_search.png";
import bfsImg from "../../assets/bfs.png";
import dfsImg from "../../assets/dfs.png";
import dijkstraImg from "../../assets/Dijkstra.png";
import bellmanFordImg from "../../assets/bellman.png";
import kruskalImg from "../../assets/Kruskal.png";
import primImg from "../../assets/prims.png";
import fibonacciDpImg from "../../assets/Fibonacci.png";
import knapsackImg from "../../assets/1knapsack.png";
import lcsImg from "../../assets/lcs.png";
import lisImg from "../../assets/lis.png";
import coinChangeImg from "../../assets/coinchnage.png";
import editDistanceImg from "../../assets/editDistance.png";
import inorderImg from "../../assets/inorder.png";
import preorderImg from "../../assets/preorder.png";
import postorderImg from "../../assets/postorder.png";
import bstInsertImg from "../../assets/bst.png";
import avlTreeImg from "../../assets/avl.png";

export const sortingAlgorithms = [
    {
        id: "bubble",
        title: "Bubble Sort",
        shortDescription: "Swap adjacent elements if out of order.",
        description:
            "Bubble Sort repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.",
        timeComplexity: { best: "O(n)", avg: "O(n^2)", worst: "O(n^2)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Comparison",
        difficulty: "Easy",
        isFavorite: false,
        image: bubbleImg,
        color: "#f59e0b",
        youtubeLink: "https://www.youtube.com/watch?v=xli_FI7CuzA",
        docsLink: "https://www.geeksforgeeks.org/bubble-sort/",
    },
    {
        id: "insertion",
        title: "Insertion Sort",
        shortDescription: "Insert element in correct position.",
        description:
            "Builds the final sorted array one item at a time by comparing and inserting elements into their correct position.",
        timeComplexity: { best: "O(n)", avg: "O(n^2)", worst: "O(n^2)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Comparison",
        difficulty: "Easy",
        isFavorite: false,
        image: insertionImg,
        color: "#10b981",
        youtubeLink: "https://www.youtube.com/watch?v=JU767SDMDvA",
        docsLink: "https://www.geeksforgeeks.org/insertion-sort/",
    },
    {
        id: "selection",
        title: "Selection Sort",
        shortDescription: "Select minimum and place at front.",
        description:
            "Repeatedly selects the minimum element from the unsorted portion and moves it to the sorted portion.",
        timeComplexity: { best: "O(n^2)", avg: "O(n^2)", worst: "O(n^2)" },
        spaceComplexity: "O(1)",
        stable: false,
        inPlace: true,
        category: "Comparison",
        difficulty: "Easy",
        isFavorite: false,
        image: selectionImg,
        color: "#3b82f6",
        youtubeLink: "https://www.youtube.com/watch?v=g-PGLbMth_g",
        docsLink: "https://www.geeksforgeeks.org/selection-sort/",
    },
    {
        id: "merge",
        title: "Merge Sort",
        shortDescription: "Divide and merge sorted halves.",
        description:
            "A divide-and-conquer algorithm that divides the array into halves, sorts them and merges them.",
        timeComplexity: { best: "O(n log n)", avg: "O(n log n)", worst: "O(n log n)" },
        spaceComplexity: "O(n)",
        stable: true,
        inPlace: false,
        category: "Comparison",
        difficulty: "Medium",
        isFavorite: false,
        image: mergeImg,
        color: "#8b5cf6",
        youtubeLink: "https://www.youtube.com/watch?v=4VqmGXwpLqc",
        docsLink: "https://www.geeksforgeeks.org/merge-sort/",
    },
    {
        id: "quick",
        title: "Quick Sort",
        shortDescription: "Partition using pivot.",
        description:
            "Picks a pivot element and partitions the array such that smaller elements are on the left and larger on the right.",
        timeComplexity: { best: "O(n log n)", avg: "O(n log n)", worst: "O(n^2)" },
        spaceComplexity: "O(log n)",
        stable: false,
        inPlace: true,
        category: "Comparison",
        difficulty: "Medium",
        isFavorite: false,
        image: quickImg,
        color: "#ef4444",
        youtubeLink: "https://www.youtube.com/watch?v=Hoixgm4-P4M",
        docsLink: "https://www.geeksforgeeks.org/quick-sort/",
    },
    {
        id: "counting",
        title: "Counting Sort",
        shortDescription: "Count frequency of elements.",
        description:
            "Counts occurrences of each element and reconstructs the sorted array.",
        timeComplexity: { best: "O(n + k)", avg: "O(n + k)", worst: "O(n + k)" },
        spaceComplexity: "O(k)",
        stable: true,
        inPlace: false,
        category: "Non-Comparison",
        difficulty: "Medium",
        isFavorite: false,
        image: countingImg,
        color: "#14b8a6",
        youtubeLink: "https://www.youtube.com/watch?v=7zuGmKfUt7s",
        docsLink: "https://www.geeksforgeeks.org/counting-sort/",
    },
    {
        id: "heap",
        title: "Heap Sort",
        shortDescription: "Use heap structure.",
        description:
            "Builds a heap and repeatedly extracts the maximum element.",
        timeComplexity: { best: "O(n log n)", avg: "O(n log n)", worst: "O(n log n)" },
        spaceComplexity: "O(1)",
        stable: false,
        inPlace: true,
        category: "Comparison",
        difficulty: "Medium",
        isFavorite: false,
        image: heapImg,
        color: "#6366f1",
        youtubeLink: "https://www.youtube.com/watch?v=2DmK_H7IdTo",
        docsLink: "https://www.geeksforgeeks.org/heap-sort/",
    },
];


export const searchingAlgorithms = [
    {
        id: "linear-search",
        title: "Linear Search",
        shortDescription: "Scan each element one by one.",
        description:
            "Sequentially checks each element of the list until a match is found or the whole list has been searched.",
        timeComplexity: { best: "O(1)", avg: "O(n)", worst: "O(n)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Search",
        difficulty: "Easy",
        isFavorite: false,
        image: linearSearchImg,
        color: "#f59e0b",
        youtubeLink: "https://www.youtube.com/watch?v=246V51AWwZM",
        docsLink: "https://www.geeksforgeeks.org/linear-search/",
    },
    {
        id: "binary-search",
        title: "Binary Search",
        shortDescription: "Halve the search space each step.",
        description:
            "Efficiently finds a target value in a sorted array by repeatedly dividing the search interval in half.",
        timeComplexity: { best: "O(1)", avg: "O(log n)", worst: "O(log n)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Search",
        difficulty: "Easy",
        isFavorite: false,
        image: binarySearchImg,
        color: "#3b82f6",
        youtubeLink: "https://www.youtube.com/watch?v=P3YID7liBug",
        docsLink: "https://www.geeksforgeeks.org/binary-search/",
    },
    {
        id: "jump-search",
        title: "Jump Search",
        shortDescription: "Jump ahead by fixed steps.",
        description:
            "Checks fewer elements by jumping ahead by fixed steps and then doing a linear search backwards.",
        timeComplexity: { best: "O(1)", avg: "O(√n)", worst: "O(√n)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Search",
        difficulty: "Medium",
        isFavorite: false,
        image: jumpSearchImg,
        color: "#10b981",
        youtubeLink: "https://www.youtube.com/watch?v=63kS6ZkMpkA",
        docsLink: "https://www.geeksforgeeks.org/jump-search/",
    },
    {
        id: "interpolation-search",
        title: "Interpolation Search",
        shortDescription: "Probe position by value estimate.",
        description:
            "Improved binary search that estimates the position of the target using an interpolation formula.",
        timeComplexity: { best: "O(1)", avg: "O(log log n)", worst: "O(n)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Search",
        difficulty: "Medium",
        isFavorite: false,
        image: interpolationSearchImg,
        color: "#8b5cf6",
        youtubeLink: "https://www.youtube.com/watch?v=DpB3I5eCDJY",
        docsLink: "https://www.geeksforgeeks.org/interpolation-search/",
    },
    {
        id: "exponential-search",
        title: "Exponential Search",
        shortDescription: "Exponentially grow range, then binary search.",
        description:
            "Finds the range where the element is present and then uses binary search within that range.",
        timeComplexity: { best: "O(1)", avg: "O(log n)", worst: "O(log n)" },
        spaceComplexity: "O(1)",
        stable: true,
        inPlace: true,
        category: "Search",
        difficulty: "Medium",
        isFavorite: false,
        image: exponentialSearchImg,
        color: "#ef4444",
        youtubeLink: "https://www.youtube.com/watch?v=BDVYtuWXgXE",
        docsLink: "https://www.geeksforgeeks.org/exponential-search/",
    },
];


export const graphAlgorithms = [
    {
        id: "bfs",
        title: "BFS",
        shortDescription: "Explore level by level.",
        description:
            "Breadth-First Search explores all neighbors at the present depth before moving on to nodes at the next depth level.",
        timeComplexity: { best: "O(V+E)", avg: "O(V+E)", worst: "O(V+E)" },
        spaceComplexity: "O(V)",
        stable: true,
        inPlace: false,
        category: "Graph",
        difficulty: "Easy",
        isFavorite: false,
        image: bfsImg,
        color: "#3b82f6",
        youtubeLink: "https://www.youtube.com/watch?v=-tgVpUgsQ5k",
        docsLink: "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/",
    },
    {
        id: "dfs",
        title: "DFS",
        shortDescription: "Explore as deep as possible first.",
        description:
            "Depth-First Search explores as far as possible along each branch before backtracking.",
        timeComplexity: { best: "O(V+E)", avg: "O(V+E)", worst: "O(V+E)" },
        spaceComplexity: "O(V)",
        stable: true,
        inPlace: false,
        category: "Graph",
        difficulty: "Easy",
        isFavorite: false,
        image: dfsImg,
        color: "#10b981",
        youtubeLink: "https://www.youtube.com/watch?v=Urx87-NMm6c",
        docsLink: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
    },
    {
        id: "dijkstra",
        title: "Dijkstra's",
        shortDescription: "Shortest path with non-negative weights.",
        description:
            "Finds the shortest path between nodes in a weighted graph with non-negative edge weights.",
        timeComplexity: { best: "O(V^2)", avg: "O(V^2)", worst: "O(V^2)" },
        spaceComplexity: "O(V)",
        stable: false,
        inPlace: false,
        category: "Graph",
        difficulty: "Medium",
        isFavorite: false,
        image: dijkstraImg,
        color: "#f59e0b",
        youtubeLink: "https://www.youtube.com/watch?v=GazC3A4OQTE",
        docsLink: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
    },
    {
        id: "bellman-ford",
        title: "Bellman-Ford",
        shortDescription: "Shortest path with negative weights.",
        description:
            "Computes shortest paths from a source vertex to all others, handling negative edge weights.",
        timeComplexity: { best: "O(VE)", avg: "O(VE)", worst: "O(VE)" },
        spaceComplexity: "O(V)",
        stable: false,
        inPlace: false,
        category: "Graph",
        difficulty: "Hard",
        isFavorite: false,
        image: bellmanFordImg,
        color: "#ef4444",
        youtubeLink: "https://www.youtube.com/watch?v=FtN3BYH2Zes",
        docsLink: "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/",
    },
    {
        id: "kruskal",
        title: "Kruskal's MST",
        shortDescription: "Build MST by cheapest edges.",
        description:
            "Finds a minimum spanning tree by greedily adding the cheapest edge that doesn't form a cycle.",
        timeComplexity: { best: "O(E log E)", avg: "O(E log E)", worst: "O(E log E)" },
        spaceComplexity: "O(V)",
        stable: false,
        inPlace: false,
        category: "Graph",
        difficulty: "Medium",
        isFavorite: false,
        image: kruskalImg,
        color: "#8b5cf6",
        youtubeLink: "https://www.youtube.com/watch?v=4ZlRH0eK-qQ",
        docsLink: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    },
    {
        id: "prim",
        title: "Prim's MST",
        shortDescription: "Grow MST from a starting vertex.",
        description:
            "Builds a minimum spanning tree by greedily growing it one vertex at a time from a starting node.",
        timeComplexity: { best: "O(V^2)", avg: "O(V^2)", worst: "O(V^2)" },
        spaceComplexity: "O(V)",
        stable: false,
        inPlace: false,
        category: "Graph",
        difficulty: "Medium",
        isFavorite: false,
        image: primImg,
        color: "#14b8a6",
        youtubeLink: "https://www.youtube.com/watch?v=oP2-8ysT3QQ",
        docsLink: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/",
    },
];

export const dpAlgorithms = [
    {
        id: "fibonacci-dp",
        title: "Fibonacci (DP)",
        shortDescription: "Memoized Fibonacci sequence.",
        description:
            "Computes Fibonacci numbers efficiently using memoization to avoid redundant calculations.",
        timeComplexity: { best: "O(n)", avg: "O(n)", worst: "O(n)" },
        spaceComplexity: "O(n)",
        stable: true,
        inPlace: false,
        category: "DP",
        difficulty: "Easy",
        isFavorite: false,
        image: fibonacciDpImg,
        color: "#10b981",
        youtubeLink: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
        docsLink: "https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/",
    },
    {
        id: "knapsack",
        title: "0/1 Knapsack",
        shortDescription: "Max value within weight limit.",
        description:
            "Selects items with maximum total value without exceeding a weight capacity. Each item is used at most once.",
        timeComplexity: { best: "O(nW)", avg: "O(nW)", worst: "O(nW)" },
        spaceComplexity: "O(nW)",
        stable: false,
        inPlace: false,
        category: "DP",
        difficulty: "Medium",
        isFavorite: false,
        image: knapsackImg,
        color: "#f59e0b",
        youtubeLink: "https://www.youtube.com/watch?v=8LusJS5-AGo",
        docsLink: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
    },
    {
        id: "lcs",
        title: "LCS",
        shortDescription: "Longest common subsequence.",
        description:
            "Finds the longest subsequence present in both sequences in the same order, not necessarily contiguous.",
        timeComplexity: { best: "O(mn)", avg: "O(mn)", worst: "O(mn)" },
        spaceComplexity: "O(mn)",
        stable: true,
        inPlace: false,
        category: "DP",
        difficulty: "Medium",
        isFavorite: false,
        image: lcsImg,
        color: "#8b5cf6",
        youtubeLink: "https://www.youtube.com/watch?v=sSno9rV8Rhg",
        docsLink: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
    },
    {
        id: "lis",
        title: "LIS",
        shortDescription: "Longest increasing subsequence.",
        description:
            "Finds the length of the longest subsequence of a given sequence such that all elements are in increasing order.",
        timeComplexity: { best: "O(n log n)", avg: "O(n log n)", worst: "O(n log n)" },
        spaceComplexity: "O(n)",
        stable: true,
        inPlace: false,
        category: "DP",
        difficulty: "Medium",
        isFavorite: false,
        image: lisImg,
        color: "#3b82f6",
        youtubeLink: "https://www.youtube.com/watch?v=22s1xxRvy28",
        docsLink: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/",
    },
    {
        id: "coin-change",
        title: "Coin Change",
        shortDescription: "Min coins to make a sum.",
        description:
            "Finds the minimum number of coins needed to make a given amount using available denominations.",
        timeComplexity: { best: "O(n·amount)", avg: "O(n·amount)", worst: "O(n·amount)" },
        spaceComplexity: "O(amount)",
        stable: false,
        inPlace: false,
        category: "DP",
        difficulty: "Medium",
        isFavorite: false,
        image: coinChangeImg,
        color: "#ef4444",
        youtubeLink: "https://www.youtube.com/watch?v=H9bfqozjoqs",
        docsLink: "https://www.geeksforgeeks.org/coin-change-dp-7/",
    },
    {
        id: "edit-distance",
        title: "Edit Distance",
        shortDescription: "Min edits to transform a string.",
        description:
            "Computes the minimum number of single-character edits (insert, delete, replace) to transform one string into another.",
        timeComplexity: { best: "O(mn)", avg: "O(mn)", worst: "O(mn)" },
        spaceComplexity: "O(mn)",
        stable: true,
        inPlace: false,
        category: "DP",
        difficulty: "Hard",
        isFavorite: false,
        image: editDistanceImg,
        color: "#14b8a6",
        youtubeLink: "https://www.youtube.com/watch?v=We3YDTzNXEk",
        docsLink: "https://www.geeksforgeeks.org/edit-distance-dp-5/",
    },
];

export const treeAlgorithms = [
    {
        id: "inorder",
        title: "Inorder Traversal",
        shortDescription: "Left → Root → Right.",
        description:
            "Visits nodes in left-root-right order. Produces sorted output for a BST.",
        timeComplexity: { best: "O(n)", avg: "O(n)", worst: "O(n)" },
        spaceComplexity: "O(h)",
        stable: true,
        inPlace: false,
        category: "Tree",
        difficulty: "Easy",
        isFavorite: false,
        image: inorderImg,
        color: "#10b981",
        youtubeLink: "https://www.youtube.com/watch?v=5dySuyZf9Qg",
        docsLink: "https://www.geeksforgeeks.org/inorder-traversal-of-binary-tree/",
    },
    {
        id: "preorder",
        title: "Preorder Traversal",
        shortDescription: "Root → Left → Right.",
        description:
            "Visits the root first, then the left subtree, then the right subtree. Useful for copying trees.",
        timeComplexity: { best: "O(n)", avg: "O(n)", worst: "O(n)" },
        spaceComplexity: "O(h)",
        stable: true,
        inPlace: false,
        category: "Tree",
        difficulty: "Easy",
        isFavorite: false,
        image: preorderImg,
        color: "#f59e0b",
        youtubeLink: "https://www.youtube.com/watch?v=RlUu72JrOCQ",
        docsLink: "https://www.geeksforgeeks.org/preorder-traversal-of-binary-tree/",
    },
    {
        id: "postorder",
        title: "Postorder Traversal",
        shortDescription: "Left → Right → Root.",
        description:
            "Visits left subtree, right subtree, then root. Useful for deleting trees.",
        timeComplexity: { best: "O(n)", avg: "O(n)", worst: "O(n)" },
        spaceComplexity: "O(h)",
        stable: true,
        inPlace: false,
        category: "Tree",
        difficulty: "Easy",
        isFavorite: false,
        image: postorderImg,
        color: "#3b82f6",
        youtubeLink: "https://www.youtube.com/watch?v=COQOU6klsBg",
        docsLink: "https://www.geeksforgeeks.org/postorder-traversal-of-binary-tree/",
    },
    {
        id: "bst-insert",
        title: "BST Insert",
        shortDescription: "Insert into binary search tree.",
        description:
            "Inserts a new key into a binary search tree while maintaining the BST property.",
        timeComplexity: { best: "O(log n)", avg: "O(log n)", worst: "O(n)" },
        spaceComplexity: "O(h)",
        stable: true,
        inPlace: true,
        category: "Tree",
        difficulty: "Easy",
        isFavorite: false,
        image: bstInsertImg,
        color: "#8b5cf6",
        youtubeLink: "https://www.youtube.com/watch?v=wcIRPqTR3Kc",
        docsLink: "https://www.geeksforgeeks.org/insertion-in-binary-search-tree/",
    },
    {
        id: "avl-tree",
        title: "AVL Tree",
        shortDescription: "Self-balancing BST.",
        description:
            "A self-balancing binary search tree where heights of subtrees differ by at most 1, ensuring O(log n) operations.",
        timeComplexity: { best: "O(log n)", avg: "O(log n)", worst: "O(log n)" },
        spaceComplexity: "O(n)",
        stable: true,
        inPlace: true,
        category: "Tree",
        difficulty: "Hard",
        isFavorite: false,
        image: avlTreeImg,
        color: "#ef4444",
        youtubeLink: "https://www.youtube.com/watch?v=jDM6_TnYIqE",
        docsLink: "https://www.geeksforgeeks.org/introduction-to-avl-tree/",
    },
];

export const allCategories = [
    { key: "sorting",   label: "Sorting",            icon: "↕",  algos: sortingAlgorithms   },
    { key: "searching", label: "Searching",           icon: "🔍", algos: searchingAlgorithms },
    { key: "graph",     label: "Graph",               icon: "◎",  algos: graphAlgorithms     },
    { key: "dp",        label: "Dynamic Programming", icon: "⊞",  algos: dpAlgorithms        },
    { key: "tree",      label: "Tree",                icon: "🌲", algos: treeAlgorithms      },
];

export const allAlgos = [
    ...sortingAlgorithms,
    ...searchingAlgorithms,
    ...graphAlgorithms,
    ...dpAlgorithms,
    ...treeAlgorithms,
];
